
export enum ErrorCodes {
  // REGISTRO
  EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED',
  REGISTRATION_FAILED = 'REGISTRATION_FAILED',

  // LOGIN
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_NOT_VERIFIED = 'ACCOUNT_NOT_VERIFIED',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  LOGIN_FAILED = 'LOGIN_FAILED',

  // TOKENS / SESIÓN
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  TOKEN_INVALID = 'TOKEN_INVALID',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // GENERAL
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
}